Feature/weaviate unit test
analitiq-ai/analitiq pull request #12
Opened 2024-06-08 21:38 UTC by hotbrainy

Added vectordb/webiate unittest code.

2024-06-11 14:19 UTC, kirill-andr requested changes

2024-06-11 14:19 UTC, kirill-andr commented on libs/tests/schema2.sql
@hotbrainy do we need this file if it is empty?

2024-06-11 14:19 UTC, kirill-andr commented on libs/tests/public.sql
@hotbrainy do we need this file if it is empty?

2024-06-11 14:19 UTC, kirill-andr commented on .idea/.gitignore
@hotbrainy the directory .idea should be in .gitignore. It should not be part of the PR

2024-06-11 14:19 UTC, kirill-andr commented on .idea/analitiq.iml
@hotbrainy the directory .idea should be in .gitignore. It should not be part of the PR

2024-06-11 14:19 UTC, kirill-andr commented on .idea/misc.xml
@hotbrainy the directory .idea should be in .gitignore. It should not be part of the PR

2024-06-11 14:19 UTC, kirill-andr commented on poetry.lock.backup
@hotbrainy  does this file need to be part of the PR?

2024-06-11 14:26 UTC, hotbrainy commented on libs/tests/schema2.sql
if we dont need, we can remove both in file and code.

2024-06-11 14:26 UTC, hotbrainy commented on .idea/.gitignore
OK, will fix that

2024-06-11 14:27 UTC, hotbrainy commented on .idea/analitiq.iml
OK, will fix that

2024-06-11 14:27 UTC, hotbrainy commented on .idea/misc.xml
OK, will fix that

2024-06-11 15:25 UTC, hotbrainy commented on .gitignore
I added `.idea ` folder here

2024-06-13 07:59 UTC, kirill-andr commented
Closing it as the test was manually merged into Master

2024-06-13 07:59 UTC, closed without merging